/**
 * Unified Adaptive Reasoning Engine (UARE) — deterministic decision logic
 * for the "SOP type coverage gap" case (spec: `.kiro/specs/unified-adaptive-
 * reasoning-engine/`, design.md §3–§5).
 *
 * When an injected incident triggers none of `article1`–`article6`
 * (`triggered_articles` is empty), the existing recommendation prompt
 * (`packages/ai-generator/src/recommendation-generator.ts`) is left with
 * "觸發 SOP 條款: 無" and an instruction not to fabricate — a dead end that
 * pushes the LLM toward refusal or hallucination. This module gives that
 * situation a deterministic, real-data-grounded fallback:
 *
 * - `resolveSopMatch` turns the existing `triggered_articles` output into an
 *   explicit boolean judgment (R1).
 * - `UNIVERSAL_DEFENSE_PRINCIPLES` is a fixed, non-official principle set
 *   (R2) — explicitly NOT a new SOP article.
 * - `selectGroundingCandidates` grounds "peripheral guidance" in real,
 *   currently-low-congestion road segments from the official road network
 *   (R3, R6, R7) — never a fabricated road name.
 *
 * @module domain/rule_engine/universal_defense
 */

import type {
  GroundingCandidate,
  SopMatchResult,
  UniversalPrinciple,
} from '@city-commander/shared-schemas';
import type { RoadNetworkModel } from '../road_network/road_network_model.js';
import { classifySegments } from './classification_engine.js';
import { CAPACITY_THRESHOLD } from './article2.js';

// ─── Requirement 1: SOP match judgment ────────────────────────────────────

/**
 * Determine SOP coverage status from the existing `triggered_articles`
 * output. Pure projection — does not evaluate any trigger condition itself.
 *
 * @param triggeredArticles - `articles.triggered_articles` from `aggregateArticles`
 */
export function resolveSopMatch(triggeredArticles: readonly number[]): SopMatchResult {
  const matched = triggeredArticles.length > 0;
  return {
    sop_matched: matched,
    sop_authority: matched ? 'OFFICIAL_SOP' : 'SYSTEM_DEFAULT_PRINCIPLE',
  };
}

// ─── Requirement 2: Universal defense principles ──────────────────────────

/**
 * The three universal traffic-defense principles UARE falls back to when no
 * official SOP article applies. Fixed, decision-core-sourced text — never
 * generated by the LLM. Not a new SOP article: `sop_authority` for any
 * decision that uses these is always `SYSTEM_DEFAULT_PRINCIPLE`, never
 * `OFFICIAL_SOP`.
 */
export const UNIVERSAL_DEFENSE_PRINCIPLES: readonly UniversalPrinciple[] = [
  {
    principle_id: 'UPSTREAM_CONTAINMENT',
    title: '上游截流',
    description: '於事故點前 1～2 個路口縮減車道或限制車輛進入，避免車流持續匯入事故路段',
  },
  {
    principle_id: 'PERIMETER_GUIDANCE',
    title: '周邊引導',
    description: '將車流引導至當前實測壅塞度最低之實體備用道路，不引導至未經驗證之路段',
  },
  {
    principle_id: 'PUBLIC_NOTIFICATION',
    title: '資訊通報',
    description: '透過 CMS 看板與多語廣播即時通報事故與改道資訊',
  },
];

// ─── Requirement 3, 6, 7: Grounding candidate selection ───────────────────

/** Maximum number of grounding candidates returned (requirements.md R3 AC5). */
const MAX_GROUNDING_CANDIDATES = 3;

export interface GroundingResult {
  readonly candidates: readonly GroundingCandidate[];
  readonly reason: string | null;
}

/**
 * Deterministically select real, whitelisted, currently-low-congestion road
 * segments to ground "peripheral guidance" recommendations when no official
 * SOP article matched.
 *
 * Candidate source is `roadNetwork.alternativesOf(anchorSegmentId)` — the
 * same official field SOP-2 uses — filtered to members that exist in the
 * road network (Road_Whitelist) and meet the same capacity floor as SOP-2's
 * candidate qualification (`CAPACITY_THRESHOLD`, reused not redeclared).
 * Unlike SOP-2, no "direct intersection + upstream" constraint is applied:
 * that constraint's legitimacy comes from the SOP-2 article text itself, and
 * there is no official basis to apply it to an event type SOP-2 does not
 * cover (design.md §5.1).
 *
 * Segments with no legal saturation observation at the decision cutoff are
 * excluded, never defaulted to a fabricated value (R7 AC3).
 *
 * @param anchorSegmentId - Caller-resolved anchor (`incident.affected_segment`
 *   or `incident.affected_road`, whichever is in Road_Whitelist). The caller
 *   is responsible for this precedence (design.md §5.1) and for not calling
 *   this function at all when neither is in scope (design.md §5.3).
 * @param roadNetwork - The loaded RoadNetworkModel.
 * @param saturationOf - Bound to the same TimeAlignmentStrategy/decision
 *   cutoff already used elsewhere in the decision for this event (R7 AC1,
 *   AC2). Returns `null` when no legal prior observation exists.
 */
export function selectGroundingCandidates(
  anchorSegmentId: string,
  roadNetwork: RoadNetworkModel,
  saturationOf: (segmentId: string) => number | null,
): GroundingResult {
  const source = roadNetwork.alternativesOf(anchorSegmentId);

  const scored: Array<{ candidate: GroundingCandidate; saturation: number }> = [];
  for (const candidateId of source) {
    const segment = roadNetwork.getSegment(candidateId);
    if (segment === undefined) continue; // must be in Road_Whitelist
    if (segment.capacity_vph < CAPACITY_THRESHOLD) continue;

    const saturation = saturationOf(candidateId);
    if (saturation === null) continue; // no legal observation — exclude, never default (R7 AC3)

    scored.push({
      candidate: {
        segment_id: segment.segment_id,
        road_name: segment.name,
        saturation_score: saturation,
        capacity_vph: segment.capacity_vph,
        status_text: statusTextFor(segment.segment_id, saturation),
      },
      saturation,
    });
  }

  scored.sort((a, b) => a.saturation - b.saturation);
  const candidates = scored.slice(0, MAX_GROUNDING_CANDIDATES).map((entry) => entry.candidate);

  if (candidates.length === 0) {
    return { candidates: [], reason: 'no_grounding_candidate_available' };
  }
  return { candidates, reason: null };
}

/**
 * Maps a saturation score to its A/B classification-derived status text,
 * reusing `classifySegments`' boundary logic (0.85 / 0.95) instead of
 * redeclaring the thresholds (design.md §5.1).
 */
function statusTextFor(segmentId: string, saturation: number): GroundingCandidate['status_text'] {
  const [{ level }] = classifySegments([{ segment_id: segmentId, saturation_score: saturation }]);
  if (level === 'A') return '壅塞';
  if (level === 'B') return '注意';
  return '暢通';
}
