import { useEffect, useState } from 'react';

interface BuildMetadata {
  branch: string;
  commit: string;
  region: string;
  buildTime: string;
}

const SAFE_FALLBACK: BuildMetadata = {
  branch: '64/demo-live-mvp',
  commit: 'local',
  region: 'us-west-2',
  buildTime: 'local build',
};

const ALLOWED_KEYS = [
  'VITE_APP_BRANCH',
  'VITE_APP_COMMIT',
  'VITE_AWS_REGION',
  'VITE_BUILD_TIME',
] as const;

function readBuildMetadata(): BuildMetadata {
  const source = (import.meta as unknown as { env: Record<string, string | undefined> }).env;
  const raw: Record<string, string | undefined> = {};
  for (const key of ALLOWED_KEYS) {
    raw[key] = source[key];
  }
  return {
    branch:
      raw.VITE_APP_BRANCH && raw.VITE_APP_BRANCH.length > 0
        ? raw.VITE_APP_BRANCH
        : SAFE_FALLBACK.branch,
    commit:
      raw.VITE_APP_COMMIT && raw.VITE_APP_COMMIT.length > 0
        ? raw.VITE_APP_COMMIT
        : SAFE_FALLBACK.commit,
    region:
      raw.VITE_AWS_REGION && raw.VITE_AWS_REGION.length > 0
        ? raw.VITE_AWS_REGION
        : SAFE_FALLBACK.region,
    buildTime:
      raw.VITE_BUILD_TIME && raw.VITE_BUILD_TIME.length > 0
        ? raw.VITE_BUILD_TIME
        : SAFE_FALLBACK.buildTime,
  };
}

interface FeatureRow {
  readonly title: string;
  readonly status: 'Coming Next';
  readonly description: string;
}

const FEATURE_ROWS: ReadonlyArray<FeatureRow> = [
  {
    title: 'Dynamic Time-Series Dashboard',
    status: 'Coming Next',
    description:
      'Real-time visualisation of traffic flow, congestion index, and incident propagation.',
  },
  {
    title: 'Live Incident Response',
    status: 'Coming Next',
    description: 'One-shot actionable commands grounded in the deterministic SOP rule engine.',
  },
  {
    title: 'Strategic Advisory',
    status: 'Coming Next',
    description: 'AI-assisted briefings generated only after the rule engine has converged.',
  },
  {
    title: 'Explainability and ETE',
    status: 'Coming Next',
    description: 'Traceable decision lineage and estimated-time-of-emergency for every directive.',
  },
  {
    title: 'Multilingual Alerting',
    status: 'Coming Next',
    description:
      'Public warning drafts in multiple languages, generated by Bedrock under strict guardrails.',
  },
];

function Header({ metadata }: { metadata: BuildMetadata }): JSX.Element {
  return (
    <header className="app-header">
      <div className="app-header__brand">
        <span className="app-header__pulse" aria-hidden="true" />
        <div>
          <h1>City Response Commander</h1>
          <p className="app-header__subtitle">AWS Live Demo Environment</p>
        </div>
      </div>
      <div className="app-header__status" role="status" aria-live="polite">
        <span className="app-header__status-dot" aria-hidden="true" />
        <span>
          Deployment Status:&nbsp;<strong>ONLINE</strong>
        </span>
      </div>
    </header>
  );
}

function MetaPanel({ metadata }: { metadata: BuildMetadata }): JSX.Element {
  return (
    <section className="meta-panel" aria-label="Deployment metadata">
      <h2>Deployment Metadata</h2>
      <dl>
        <div className="meta-panel__row">
          <dt>Region</dt>
          <dd>{metadata.region}</dd>
        </div>
        <div className="meta-panel__row">
          <dt>Branch</dt>
          <dd>{metadata.branch}</dd>
        </div>
        <div className="meta-panel__row">
          <dt>Commit</dt>
          <dd>{metadata.commit}</dd>
        </div>
        <div className="meta-panel__row">
          <dt>Build Time</dt>
          <dd>{metadata.buildTime}</dd>
        </div>
      </dl>
      <p className="meta-panel__note">Frontend Hosting Ready — awaiting backend integration.</p>
    </section>
  );
}

function FeatureGrid(): JSX.Element {
  return (
    <section className="feature-grid" aria-label="Roadmap features">
      <h2>Roadmap</h2>
      <ul>
        {FEATURE_ROWS.map((row) => (
          <li key={row.title} className="feature-card">
            <div className="feature-card__title-row">
              <h3>{row.title}</h3>
              <span className="badge badge--pending">{row.status}</span>
            </div>
            <p>{row.description}</p>
          </li>
        ))}
      </ul>
    </section>
  );
}

function Footer(): JSX.Element {
  return (
    <footer className="app-footer">
      <p>
        2026 雲湧智生黑客松 —&nbsp;Deterministic&nbsp;rules&nbsp;first, AI&nbsp;drafts&nbsp;second.
      </p>
    </footer>
  );
}

export function App(): JSX.Element {
  const [metadata] = useState<BuildMetadata>(() => readBuildMetadata());
  const [clock, setClock] = useState<string>(() => new Date().toISOString());

  useEffect(() => {
    const interval = window.setInterval(() => {
      setClock(new Date().toISOString());
    }, 1000);
    return () => window.clearInterval(interval);
  }, []);

  return (
    <div className="app">
      <Header metadata={metadata} />
      <main className="app-main">
        <MetaPanel metadata={metadata} />
        <FeatureGrid />
      </main>
      <div className="app-clock" aria-label="Live clock">
        Live clock (UTC):&nbsp;<code>{clock}</code>
      </div>
      <Footer />
    </div>
  );
}
