/**
 * `GET /reports/{decision_id}` — command-centre report + public alert
 * (design §12, §10.12, §10.13; TASK-150).
 *
 * Serves the two narrative items the commander reads: `REPORT` and
 * `PUBLIC_ALERT`, alongside the deterministic facts they must be read against.
 *
 * Two boundaries:
 *
 *  - **This handler serves stored text; it does not compose it.** Report and
 *    alert wording is generated by `ReportComposer` / `PublicAlertComposer`
 *    (TASK-113/114, Bedrock). When an item has not been written yet the field is
 *    `null` and `data_status` says so — the deterministic template fallback is
 *    the renderer's job (TASK-117), not this endpoint's. Inventing text here
 *    would put un-validated wording in front of a commander.
 *  - **Numbers never come from the narrative.** `cms_core_text`, `ete_minutes`
 *    and the evacuation routes are echoed from DecisionCore, so the response
 *    cannot disagree with the authoritative record even if an LLM wrote something
 *    inconsistent into its own text field (§9).
 *
 * @module backend/handlers/get_report_handler
 */

import { NarrativeType } from '@city-commander/shared-schemas';
import type {
  DecisionNarrative,
  PublicAlertPayload,
  ReportPayload,
} from '@city-commander/shared-schemas';
import { aggregateDecisionReadModel } from '../read_model/read_model_aggregator.js';
import type {
  DecisionReadModel,
  ReadModelDataStatus,
  ReadModelPorts,
} from '../read_model/read_model_aggregator.js';
import { ok, requirePathParameter, resolveTraceId, withErrorEnvelope } from './http_envelope.js';
import type { HttpErrorResult, HttpGetEvent, HttpResult } from './http_envelope.js';

/** Path parameter name, matching the §12 route `/reports/{decision_id}`. */
export const REPORT_DECISION_ID_PARAM = 'decision_id';

/** Deterministic facts echoed from DecisionCore, never from narrative text. */
export interface ReportDeterministicFacts {
  readonly event_id: string | null;
  readonly triggered_articles: readonly number[];
  readonly applied_formula_articles: readonly number[];
  readonly invoked_procedures: readonly string[];
  readonly primary_evacuation: string | null;
  readonly secondary_evacuation: readonly string[];
  readonly ete_minutes: number | null;
  /** LLM-prohibited official CMS wording (§10.11a). */
  readonly cms_core_text: string | null;
  readonly multilingual_required: boolean;
}

/** `GET /reports/{decision_id}` response body. */
export interface GetReportResponseBody {
  readonly schema_version: string;
  readonly trace_id: string;
  readonly decision_id: string;
  readonly data_status: ReadModelDataStatus;
  /** `null` until `ReportComposer` has written the REPORT item. */
  readonly report: ReportPayload | null;
  /** `null` until `PublicAlertComposer` has written the PUBLIC_ALERT item. */
  readonly alert: PublicAlertPayload | null;
  /** Authoritative values the report must be read against. */
  readonly facts: ReportDeterministicFacts;
  readonly provisional: boolean;
  readonly policy_version: string | null;
}

function findPayload<T>(narratives: readonly DecisionNarrative[], type: NarrativeType): T | null {
  const item = narratives.find((narrative) => narrative.narrative_type === type);
  return item === undefined ? null : (item.payload as unknown as T);
}

function toFacts(model: DecisionReadModel): ReportDeterministicFacts {
  const core = model.core;
  return {
    event_id: core?.event_id ?? null,
    triggered_articles: core?.triggered_articles ?? [],
    applied_formula_articles: core?.applied_formula_articles ?? [],
    invoked_procedures: core?.invoked_procedures ?? [],
    primary_evacuation: core?.primary_evacuation ?? null,
    secondary_evacuation: core?.secondary_evacuation ?? [],
    ete_minutes: core?.ete?.ete_minutes ?? null,
    cms_core_text: core?.cms_core_text ?? null,
    multilingual_required: core?.multilingual_required ?? false,
  };
}

/**
 * Build the `GET /reports/{decision_id}` handler.
 *
 * @returns `200` with whatever exists (report/alert may be `null`); `400` on a
 *          missing path parameter; `429`/`500` on a downstream fault
 */
export function createGetReportHandler(
  ports: ReadModelPorts,
): (event: HttpGetEvent) => Promise<HttpResult | HttpErrorResult> {
  return async (event: HttpGetEvent) => {
    const traceId = resolveTraceId(event);

    return withErrorEnvelope(traceId, async () => {
      const decisionId = requirePathParameter(event, REPORT_DECISION_ID_PARAM, traceId);

      const model = await aggregateDecisionReadModel(ports, { decisionId, traceId });

      const body: GetReportResponseBody = {
        schema_version: model.schema_version,
        trace_id: model.trace_id,
        decision_id: model.decision_id,
        data_status: model.data_status,
        report: findPayload<ReportPayload>(model.narratives, NarrativeType.REPORT),
        alert: findPayload<PublicAlertPayload>(model.narratives, NarrativeType.PUBLIC_ALERT),
        facts: toFacts(model),
        provisional: model.provisional,
        policy_version: model.policy_version,
      };

      return ok(body);
    });
  };
}
